---
- name: Configure Juniper LAB-MGMT-FW-01
  hosts: LAB-MGMT-FW-01
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos

  tasks:
    - name: Delete configuration
      junipernetworks.junos.junos_command:
        commands:
          - delete
        prompt:
          - 'Delete everything under this level? [yes,no] (no)'
        answer:
          - yes
