---
- name: Configure Juniper LAB-SW-EX2200
  hosts: LAB-SW-EX2200
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos

  tasks:
    - name: Enter configuration mode
      junipernetworks.junos.junos_command:
        commands:
          - configure
      register: config_mode_output

    - name: Configure device
      junipernetworks.junos.junos_command:
        commands:
          - set system host-name LAB-SW-EX2200
          - set system services ssh protocol-version v2
          - set interfaces me0 unit 0 family inet address 192.168.1.254/24
          - set protocols lldp interface all
          - set protocols lldp-med interface all
          - set poe interface all
          - set system root-authentication plaintext-password Pa$$w0rd
      when: config_mode_output is succeeded

    - name: Commit configuration changes
      junipernetworks.junos.junos_command:
        commands:
          - commit
      when: config_mode_output is succeeded
