---
- name: Configure Juniper LAB-MGMT-FW-01
  hosts: LAB-MGMT-FW-01
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos

  tasks:
    - name: Delete all configuration
      junipernetworks.junos.junos_config:
        state: absent
        zeroize: yes
        answer: yes
