---
- name: Configure Juniper LAB-MGMT-FW-01
  hosts: LAB-MGMT-FW-01
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos

  tasks:
    - name: Backup device configuration
      junipernetworks.junos.junos_config:
        backup: true
      register: config_result
