---
- name: Configure Juniper LAB-MGMT-FW-01
  hosts: LAB-MGMT-FW-01
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos

  tasks:
    - name: Delete configuration and Configure device
      junipernetworks.junos.junos_command:
        commands:
          - configure
          - delete access
          - delete access-profile
          - delete accounting-options
          - delete applications
          - delete apply-groups
          - delete bridge-domains
          - delete chassis
          - delete class-of-service
          - delete ethernet-switching-options
          - delete event-options
          - delete firewall
          - delete forwarding-options
          - delete groups
          - delete interfaces
          - delete multicast-snooping-options
          - delete policy-options
          - delete protocols
          - delete routing-instances
          - delete routing-options
          - delete schedulers
          - delete security
          - delete services
          - delete smtp
          - delete snmp
          - delete switch-options
          - delete system
          - delete vlans
          - set system root-authentication encrypted-password "$1$/yeH./QS$wJ/oQInebOWxKE0TdVsKR0"
          - set system host-name LAB-MGMT-FW-01
          - set system services ssh protocol-version v2
          - set system services netconf ssh
          - set interfaces ge-0/0/0 unit 0 family inet address 192.168.1.248/24
          - set security zones security-zone untrust interfaces ge-0/0/0.0 host-inbound-traffic system-services ssh
          - set security zones security-zone untrust interfaces ge-0/0/0.0 host-inbound-traffic system-services ping
          - commit
