---
- name: Configure Juniper LAB-MGMT-FW-01
  hosts: LAB-MGMT-FW-01
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos

  tasks:
    - name: Send delete and yes commands
      ansible.builtin.raw: |
        delete
        yes
      register: command_output
      delegate_to: LAB-MGMT-FW-01

    - debug:
        var: command_output.stdout_lines
