---
- name: Configure Juniper LAB-MGMT-FW-01
  hosts: LAB-MGMT-FW-01
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos

  tasks:
    - name: Send delete and yes commands
      ansible.builtin.send:
        newline: "delete\nyes\n"
      delegate_to: LAB-MGMT-FW-01
