---
- name: Configure Juniper LAB-MGMT-FW-01
  hosts: LAB-MGMT-FW-01
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos

  tasks:
    - name: Delete configuration
      expect:
        command: delete
        responses:
          'Delete everything under this level\? \[yes,no\] \(no\)': 'yes'
