---
- name: Configure Juniper Devices
  hosts: juniper_devices
  gather_facts: no
  connection: network_cli

  tasks:
    - name: collect default set of facts
      junipernetworks.junos.junos_facts:
