---
- name: Configure Juniper Devices
  hosts: juniper_devices
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos

  tasks:
    - name: Gather facts from SRX devices
      junos_facts:
        host: "{{ inventory_hostname }}"

    - name: Print facts
      debug:
        var: facts
