---
- name: Set Juniper Switches, Routers, and Firewalls Base Config
  hosts: juniper
  gather_facts: no
  connection: network_cli
  
  vars:
    ansible_network_os: junos

  tasks:
    - name: Run delete command
      junipernetworks.junos.junos_command:
        commands:
          - command: delete
            prompt: 'Delete everything under this level? \[yes,no\] \(no\)'
            answer: 'yes'
      register: delete_output

    - name: Show delete command output
      debug:
        var: delete_output.stdout_lines
