---
- name: Check Juniper Model and Hostname
  hosts: juniper
  gather_facts: no
  connection: netconf

  vars:
    ansible_network_os: junos

  tasks:
    - name: collect default set of facts
      junipernetworks.junos.junos_facts:

    - name: display gathered facts
      debug:
        var: ansible_net_facts
