---
- name: Configure Juniper Devices
  hosts: juniper_devices
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos

  tasks:
    - name: Gather legacy and resource facts
      junipernetworks.junos.junos_facts:
        gather_subset: all
        gather_network_resources: all
