---
- name: Check Juniper Model and Hostname
  hosts: juniper
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos

  tasks:
    - name: collect default set of facts
      junipernetworks.junos.junos_facts:
