---
- name: Juniper Switches, Routers, and Firewalls Base Configuration
  hosts: juniper
  gather_facts: no
  connection: netconf

  vars:
    ansible_network_os: junos
    
    interface_configs:
      - models: 
          - ex2200-c-12t-2g
          - vqfx
        config_lines: |
          delete interfaces
          set interfaces vme unit 0 family inet address {{ ansible_host }}/24
      - models:
          - vSRX
          - MX
        config_lines: |
          delete interfaces
          set interfaces fxp0 unit 0 family inet address {{ ansible_host }}/24
          set protocols lldp-med interface all

  tasks:
    - name: collect default set of facts and configuration
      junipernetworks.junos.junos_facts:
      register: juniper_output

    - name: Display Juniper System Model
      debug:
        var: juniper_output.ansible_facts.ansible_net_model

    - name: Set system config
      junipernetworks.junos.junos_config:
        lines:
          - delete system
          - set system root-authentication encrypted-password "$1$/yeH./QS$wJ/oQInebOWxKE0TdVsKR0"
          - set system host-name {{ inventory_hostname }}
          - set system services ssh root-login allow
          - set system services ssh protocol-version v2
          - set system services netconf ssh

    - name: Configure management interface
      junipernetworks.junos.junos_config:
        lines: |
          {% for intf_config in interface_configs %}
          {% if juniper_output.ansible_facts.ansible_net_model in intf_config.models %}
          {{ intf_config.config_lines }}
          {% endif %}
          {% endfor %}

