---
- name: Show Juniper Switches, Routers, and Firewalls Configuration
  hosts: juniper
  gather_facts: no
  connection: netconf

  vars:
    ansible_network_os: junos

  tasks:
    - name: collect default set of facts and configuration
      junipernetworks.junos.junos_hostname:
        config:
          hostname: "{{ inventory_hostname }}"
        state: replaced
