---
- name: Juniper Switches, Routers, and Firewalls Base Configuration
  hosts: juniper
  gather_facts: no
  connection: netconf

  vars:
    ansible_network_os: junos
    mgmt_interface: me0
    test_interface: ge-0/0/0

  tasks:
    - name: Set password and ssh
      junipernetworks.junos.junos_config:
        lines:
        - delete system
        - set system root-authentication encrypted-password "$1$/yeH./QS$wJ/oQInebOWxKE0TdVsKR0"
        - set system host-name {{ inventory_hostname }}
        - set system services ssh root-login allow
        - set system services ssh protocol-version v2
        - set system services netconf ssh
        - set interfaces {{ test_interface }} unit 0 family inet address 192.168.2.254/24
        
    - name: configure name servers
      junipernetworks.junos.junos_system:
        name_servers:
        - 8.8.8.8
        - 8.8.4.4
        state: present
