---
- name: Check Juniper Model and Hostname
  hosts: juniper
  gather_facts: no
  connection: netconf

  vars:
    ansible_network_os: junos

  tasks:
    - name: collect default set of facts and configuration
      junipernetworks.junos.junos_facts:
        gather_subset: all
        gather_network_resources: all
      register: juniper_output

    - name: Display Juniper System Model
      debug:
        var: juniper_output.ansible_facts.ansible_net_model
