---
- name: Check Juniper Model and Hostname
  hosts: juniper
  gather_facts: yes
  connection: netconf

  tasks:
    - name: Display Juniper System Model
      debug:
        var: ansible_net_model
      when: "'Juniper' in ansible_facts['ansible_vendor']"
