---
- name: Show Juniper Switches, Routers, and Firewalls Configuration
  hosts: LAB-SW-EX2200
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos
    ansible_network_cli_timeout: 60

  tasks:
    - name: Show configuration in set format
      junipernetworks.junos.junos_command:
        commands:
          - show configuration
        display: set
      register: config_output
