- name: Gather Juniper device info
  hosts: juniper_devices
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Configure ansible_network_os for Juniper devices
      set_fact:
        ansible_network_os: junos
      when: inventory_hostname in groups['juniper_devices']

    - name: Collect default set of Juniper facts
      junipernetworks.junos.junos_facts:
        gather_subset: default
      register: juniper_facts

    - name: Print Juniper device info
      debug:
        var: juniper_facts
