---
- name: Configure Juniper Devices
  hosts: juniper_devices
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos

  tasks:
  - name: Check device type
    junos_version:
      host: "{{ inventory_hostname }}"
      gather_facts: no
    register: junos_version

  - name: Print device type
    debug:
      var: junos_version.device_type
