---
- name: Juniper Switches, Routers, and Firewalls Base Configuration
  hosts: juniper
  gather_facts: no
  connection: netconf

  vars:
    ansible_network_os: junos

  tasks:
    - name: Set hostname for devices
      junipernetworks.junos.junos_hostname:
        config:
          hostname: "{{ inventory_hostname }}"
        state: replaced
        
    - name: Set hostname for devices
      junipernetworks.junos.junos_config:
        lines:
        - set system root-authentication encrypted-password "$1$/yeH./QS$wJ/oQInebOWxKE0TdVsKR0"

    - name: configure name servers
      junipernetworks.junos.junos_system:
        name_servers:
        - 8.8.8.8
        - 8.8.4.4
        state: present
