---
- name: Check Juniper Model and Hostname
  hosts: juniper
  gather_facts: no
  connection: netconf

  vars:
    ansible_network_os: junos

- name: collect default set of facts and configuration
  junipernetworks.junos.junos_facts:
    gather_subset: config
