---
- name: Juniper Switches, Routers, and Firewalls Base Configuration
  hosts: juniper
  gather_facts: no
  connection: netconf
  vars:
    ansible_network_os: junos

  tasks:
    - name: Set system configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete system
          - set system root-authentication encrypted-password "$1$/yeH./QS$wJ/oQInebOWxKE0TdVsKR0"
          - set system services ssh root-login allow
          - set system services ssh protocol-version v2
          - set system services netconf ssh
