---
- name: Juniper Switches, Routers, and Firewalls Base Configuration
  hosts: juniper
  gather_facts: no
  connection: netconf

  vars:
    ansible_network_os: junos

  tasks:
    - name: collect default set of facts and configuration
      junipernetworks.junos.junos_hostname:
        config:
          hostname: "{{ inventory_hostname }}"
        state: replaced

    - name: configure name servers
      junipernetworks.junos.junos_system:
        name_servers:
        - 8.8.8.8
        - 8.8.4.4
