---
- name: Configure Juniper SRX Firewalls
  hosts: juniper_srx_firewalls
  gather_facts: no
  connection: netconf
  serial: 1  # Execute tasks serially, one host at a time
  vars:
    ansible_network_os: junos
    retry_max: 3  # Maximum number of retry attempts
    retry_delay: 10  # Delay between retry attempts (in seconds)
  tasks:
    - name: Load Junos configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete groups
          - delete system
          - delete interfaces
          - set groups node0 interfaces fxp0 unit 0 family inet address {{ ansible_host }}/24
          - set groups node1 interfaces fxp0 unit 0 family inet address {{ ansible_host }}/24
          - set groups node0 system host-name {{ inventory_hostname }}
          - set groups node1 system host-name {{ inventory_hostname }}
          - set apply-groups ${node}
          - set system root-authentication encrypted-password $1$/yeH./QS$wJ/oQInebOWxKE0TdVsKR0
          - set system services ssh root-login allow
          - set system services ssh protocol-version v2
          - set system services netconf ssh
          - set interfaces fab0 fabric-options member-interfaces ge-0/0/0
          - set interfaces fab1 fabric-options member-interfaces ge-7/0/0
      retries: "{{ retry_max }}"
      delay: "{{ retry_delay }}"
      until: not result|failed
      ignore_errors: yes  # Continue with other tasks even if this one fails
