---
- name: Configure Juniper SRX Firewalls
  hosts: juniper_srx_firewalls
  gather_facts: no
  connection: netconf
  serial: 1
  vars:
    ansible_network_os: junos
    retry_max: 3
    retry_delay: 10
    junos_config_timeout: 120  # Increased timeout value

  tasks:
    - name: Load Junos configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete groups
          - delete system
          - delete interfaces
          - set interfaces fxp0 unit 0 family inet address {{ ansible_host }}/24
          - set system host-name {{ inventory_hostname }}
          - set system root-authentication encrypted-password $1$/yeH./QS$wJ/oQInebOWxKE0TdVsKR0
          - set system services ssh root-login allow
          - set system services ssh protocol-version v2
          - set system services netconf ssh
          - set interfaces fab0 fabric-options member-interfaces ge-0/0/0
          - set interfaces fab1 fabric-options member-interfaces ge-7/0/0
        timeout: "{{ junos_config_timeout }}"  # Use the extended timeout value
      retries: "{{ retry_max }}"
      delay: "{{ retry_delay }}"
      ignore_errors: yes
