---
- name: Configure Virtual Juniper QFX Switches
  hosts: juniper_qfx_switches
  gather_facts: no
  connection: netconf

  vars:
    ansible_network_os: junos

  tasks:
    - name: Set Aggregated Devices Ethernet Device Count
      junipernetworks.junos.junos_config:
        lines:
          - set chassis aggregated-devices ethernet device-count 2

    - name: Delete Protocols Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete protocols

    - name: Delete Forwarding-Options Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete forwarding-options

    - name: Delete Interfaces and Set IP Addresses
      junipernetworks.junos.junos_config:
        lines:
          - delete interfaces
          - set interfaces em0 unit 0 family inet address {{ ansible_host }}/{{ qfx_mgmt_subnet }}
          - set interfaces em1 unit 0 family inet address 169.254.0.2/24
          - set interfaces {{ ae0_link1_interface }} description ae0
          - set interfaces {{ ae0_link2_interface }} description ae0
          - set interfaces {{ ae0_link1_interface }} gigether-options 802.3ad ae0
          - set interfaces {{ ae0_link2_interface }} gigether-options 802.3ad ae0
          - set interfaces ae0 aggregated-ether-options lacp active
          - set interfaces ae0 aggregated-ether-options lacp periodic fast
          - set interfaces {{ vrrp_group_1_interface }} unit 0 family inet address {{ vrrp_group_1_ipaddress }}/{{ vrrp_group_1_subnet }} vrrp-group {{ vrrp_group_1_group }} virtual-address {{ vrrp_group_1_vip }}
          - set interfaces {{ vrrp_group_1_interface }} unit 0 family inet address {{ vrrp_group_1_ipaddress }}/{{ vrrp_group_1_subnet }} vrrp-group {{ vrrp_group_1_group }} priority {{ vrrp_group_1_priority }}
          - set interfaces {{ vrrp_group_1_interface }} unit 0 family inet address {{ vrrp_group_1_ipaddress }}/{{ vrrp_group_1_subnet }} vrrp-group {{ vrrp_group_1_group }} preempt
          - set interfaces {{ vrrp_group_1_interface }} unit 0 family inet address {{ vrrp_group_1_ipaddress }}/{{ vrrp_group_1_subnet }} vrrp-group {{ vrrp_group_1_group }} accept-data

    - name: Delete VLANs Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete vlans

    - name: Delete Groups Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete groups

    - name: Delete Security Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete security

    - name: Delete Apply-Groups Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete apply-groups

    - name: Delete and Set System Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete system
          - set system root-authentication encrypted-password "$1$/yeH./QS$wJ/oQInebOWxKE0TdVsKR0"
          - set system services ssh root-login allow
          - set system services ssh protocol-version v2
          - set system services netconf ssh
          - set system login class view-config permissions view-configuration
          - set system login class view-config allow-commands "show configuration"
          - set system login class view-config deny-commands "(clear)|(file)|(file show)|(help)|(load)|(monitor)|(op)|(request)|(save)|(set)|(start)|(test)"
          - set system login class view-config allow-configuration "show configuration"
          - set system login class view-config deny-configuration all
          - set system login user LAB-JUNIPER-SW-OPERATOR class operator
          - set system login user LAB-JUNIPER-SW-READONLY class read-only
          - set system login user LAB-JUNIPER-SW-SUPERUSER class super-user
          - set system login user LAB-JUNIPER-SW-VIEWCONFIG class view-config
          - set system time-zone EST
          - set system authentication-order password
          - set system authentication-order radius
          - set system radius-options password-protocol mschap-v2

    - name: Configure Juniper QFX Switches Hostname
      junipernetworks.junos.junos_hostname:
        config:
          hostname: "{{ inventory_hostname }}"
        state: replaced

    - name: Juniper LLDP Config
      junipernetworks.junos.junos_lldp_interfaces:
        config:
          - name: all
        state: replaced

    - name: Replace Static Routes
      junipernetworks.junos.junos_static_routes:
        config:
          - address_families:
            - afi: ipv4
              routes:
                - dest: "{{ default_static_route1 }}"
                  next_hop:
                    - forward_router_address: "{{ default_static_route1_next_hop }}"
        state: replaced
