---
- name: Configure Juniper QFX Switches
  hosts: juniper_qfx_switches
  gather_facts: no
  connection: netconf

  vars:
    ansible_network_os: junos

  tasks:
    - name: Set Juniper QFX Switches Base Config
      junipernetworks.junos.junos_command:
        commands:
          - configure
          - set system host-name {{ inventory_hostname }}
          - set protocols lldp interface all
          - set protocols lldp-med interface all
          - set interfaces fxp0 unit 0 family inet address {{ inventory_hostname_ip }}
          - commit
