---
- name: Configure Juniper QFX Switches
  hosts: juniper_qfx_switches
  gather_facts: no
  connection: netconf

  vars:
    ansible_network_os: junos

  tasks:
    - name: Configure Junos settings
      junipernetworks.junos.junos_config:
        lines:
          - delete groups
          - delete security
          - delete apply-groups
          - delete system
          - delete interfaces
          - delete forwarding-options
          - delete protocols
          - delete vlans
          - set interfaces em0 unit 0 family inet address {{ ansible_host }}/{{ qfx_mgmt_subnet }}
          - set system root-authentication encrypted-password "$1$/yeH./QS$wJ/oQInebOWxKE0TdVsKR0"
          - set system services ssh root-login allow
          - set system services ssh protocol-version v2
          - set system services netconf ssh

    - name: Configure Juniper QFX Switches Hostname
      junipernetworks.junos.junos_hostname:
        config:
          hostname: {{ inventory_hostname }}
        state: replaced
