---
- name: Configure Virtual Juniper QFX Switches
  hosts: juniper_qfx_switches
  gather_facts: no
  connection: netconf

  vars:
    ansible_network_os: junos

  tasks:
    - name: Delete Protocols Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete protocols

    - name: Delete Forwarding-Options Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete forwarding-options

    - name: Delete Interfaces and Set IP Addresses
      junipernetworks.junos.junos_config:
        lines:
          - delete interfaces
          - set interfaces em0 unit 0 family inet address {{ ansible_host }}/{{ qfx_mgmt_subnet }}
          - set interfaces em1 unit 0 family inet address 169.254.0.2/24
          - set interfaces irb unit {{ vrrp_group_1_vlan }} family inet address {{ vrrp_group_1_ipaddress }}/{{ vrrp_group_1_subnet }} vrrp-group {{ vrrp_group_1_group }} virtual-address {{ vrrp_group_1_vip }} 
          - set interfaces irb unit {{ vrrp_group_1_vlan }} family inet address {{ vrrp_group_1_ipaddress }}/{{ vrrp_group_1_subnet }} vrrp-group {{ vrrp_group_1_group }} priority {{ vrrp_group_1_priority }} 
          - set interfaces irb unit {{ vrrp_group_1_vlan }} family inet address {{ vrrp_group_1_ipaddress }}/{{ vrrp_group_1_subnet }} vrrp-group {{ vrrp_group_1_group }} preempt
          - set interfaces irb unit {{ vrrp_group_1_vlan }} family inet address {{ vrrp_group_1_ipaddress }}/{{ vrrp_group_1_subnet }} vrrp-group {{ vrrp_group_1_group }} accept-data 

    - name: Delete VLANs Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete vlans
          - set vlans SW-UPLINK vlan-id {{ vrrp_group_1_vlan }}
          - set vlans SW-UPLINK l3-interface irb.{{ vrrp_group_1_vlan }}

    - name: Delete Groups Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete groups

    - name: Delete Security Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete security

    - name: Delete Apply-Groups Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete apply-groups

    - name: Delete and Set System Configuration
      junipernetworks.junos.junos_config:
        lines:
          - delete system
          - set system root-authentication encrypted-password "$1$/yeH./QS$wJ/oQInebOWxKE0TdVsKR0"
          - set system services ssh root-login allow
          - set system services ssh protocol-version v2
          - set system services netconf ssh
          - set system login class view-config permissions view-configuration
          - set system login class view-config allow-commands "show configuration"
          - set system login class view-config deny-commands "(clear)|(file)|(file show)|(help)|(load)|(monitor)|(op)|(request)|(save)|(set)|(start)|(test)"
          - set system login class view-config allow-configuration "show configuration"
          - set system login class view-config deny-configuration all
          - set system login user LAB-JUNIPER-SW-OPERATOR class operator
          - set system login user LAB-JUNIPER-SW-READONLY class read-only
          - set system login user LAB-JUNIPER-SW-SUPERUSER class super-user
          - set system login user LAB-JUNIPER-SW-VIEWCONFIG class view-config
          - set system time-zone EST
          - set system authentication-order password
          - set system authentication-order radius
          - set system radius-options password-protocol mschap-v2

    - name: Configure Juniper QFX Switches Hostname
      junipernetworks.junos.junos_hostname:
        config:
          hostname: "{{ inventory_hostname }}"
        state: replaced
