- name: Configure Juniper EX Switches
  hosts: juniper_ex_switches
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: junos
    ansible_network_cli_timeout: 60

  tasks:
    - name: Delete Juniper EX Switches Config
      junipernetworks.junos.junos_command:
        commands:
          - configure
          - delete access
          - delete access-profile
          - delete accounting-options
          - delete apply-groups
          - delete chassis
          - delete class-of-service
          - delete ethernet-switching-options
          - delete event-options
          - delete firewall
          - delete forwarding-options
          - delete groups
          - delete interfaces
          - delete multi-chassis
          - delete poe
          - delete policy-options
          - delete protocols
          - delete redundant-power-system
          - delete routing-instances
          - delete routing-options
          - delete security
          - delete services
          - delete snmp
          - delete system
          - delete virtual-chassis
          - delete vlans

    - name: Set Juniper EX Switches Config
      junipernetworks.junos.junos_command:
        commands:
          - configure
          - set poe interface all
          - set protocols lldp interface all
          - set protocols lldp-med interface all
          - set interfaces me0 unit 0 family inet address {{ ansible_host }}/24
          - set system host-name {{ inventory_hostname }}
          - set system root-authentication encrypted-password "$1$/yeH./QS$wJ/oQInebOWxKE0TdVsKR0"
          - set system services netconf ssh
          - set system services ssh protocol-version v2
          - commit
