- name: Copy SSH key to ESXi hosts
  hosts: esxi
  connection: local
  gather_facts: no
  become: no
  vars:
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'

  tasks:
    - name: Copy SSH key to authorized_keys
      ansible.builtin.shell: cat /root/.ssh/id_rsa.pub | ssh root@{{ ansible_host }} 'cat >> /etc/ssh/keys-root/authorized_keys'
