---
- name: Copy SSH public key to ESXi host
  hosts: esxi
  gather_facts: false
  become: true

  tasks:
    - name: Copy public key contents to authorized_keys file on ESXi host
      lineinfile:
        line: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        path: /etc/ssh/keys-root/authorized_keys
        create: yes
        mode: '0600'
