- name: Copy SSH key to ESXi hosts
  hosts: esxi
  connection: local
  gather_facts: no
  become: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'

  tasks:
    - name: Copy SSH key to authorized_keys
      ansible.builtin.command:
        cmd: 'cat /root/.ssh/id_rsa.pub | ssh root@{{ ansible_host }} "cat >> /etc/ssh/keys-root/authorized_keys"'
