---
- name: Copy SSH public key to ESXi host
  hosts: esxi
  gather_facts: false
  become: true

  tasks:
    - name: Fetch public key file from control machine
      fetch:
        src: /root/.ssh/id_rsa.pub
        dest: /tmp/id_rsa.pub
        flat: yes

    - name: Create authorized_keys file
      template:
        src: /tmp/id_rsa.pub
        dest: /etc/ssh/keys-root/authorized_keys
        mode: '0600'
