---
- name: Copy SSH public key to ESXi host
  hosts: esxi_host
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Fetch public key contents
      command: cat /root/.ssh/id_rsa.pub
      register: public_key

    - name: Copy public key to authorized_keys
      copy:
        content: "{{ public_key.stdout }}"
        dest: /etc/ssh/keys-root/authorized_keys
        mode: '0644'
        become: true
