- name: Copy SSH key to ESXi hosts
  hosts: esxi
  gather_facts: no
  become: yes

  tasks:
  - name: Set the authorized ssh keys for the root user
    copy:
      src: /root/.ssh/id_rsa.pub
      dest: /etc/ssh/keys-root/authorized_keys
      owner: root
      group: root
      mode: '0600'
