- name: Copy SSH public key and configure authorized keys
  hosts: esxi
  gather_facts: no
  become: yes

  tasks:
    - name: Copy SSH public key to ESXi host
      command: "cat files/id_rsa.pub | ssh root@192.168.1.253 'cat >> /etc/ssh/keys-root/authorized_keys'"
