---
- name: Copy SSH keys to ESXi hosts
  hosts: esxi
  gather_facts: no
  become: yes

  tasks:
    - name: Check device type
      setup:
      register: device_info

    - name: Copy SSH key to authorized_keys
      command: cat ~/.ssh/id_rsa.pub | ssh root@{{ ansible_host }} 'cat >> /etc/ssh/keys-root/authorized_keys'
      environment:
        SSH_AUTH_SOCK: no
      when: device_info.ansible_facts.ansible_system == "VMware ESXi"
