---
- name: Copy SSH public key to ESXi host
  hosts: esxi
  gather_facts: false
  become: true

  tasks:
    - name: Copy public key contents to authorized_keys file on ESXi host
      copy:
        content: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        dest: /etc/ssh/keys-root/authorized_keys
        mode: '0600'
