- name: Copy SSH public key and handle key fingerprint
  hosts: esxi
  become: true
  
  tasks:
    - name: Copy SSH public key to remote host
      copy:
        src: root/id_rsa.pub
        dest: /etc/ssh/keys-root/authorized_keys+
        mode: '0644'
        owner: root
        group: root
    
    - name: Retrieve key fingerprint for first time connection
      shell: ssh-keyscan -t rsa localhost
      register: ssh_fingerprint
      changed_when: false
    
    - name: Add key fingerprint to known_hosts file
      lineinfile:
        path: /root/.ssh/known_hosts
        line: "{{ ssh_fingerprint.stdout }}"
        create: yes
        mode: '0644'
        owner: root
        group: root
      when: ssh_fingerprint.stdout is defined
