- name: Copy SSH public key and configure authorized keys
  hosts: esxi
  gather_facts: no
  become: yes

  tasks:
    - name: Copy SSH public key to ESXi host
      shell: "cat root/.ssh/id_rsa.pub | ssh root@{{ ansible_host }} 'cat >> /etc/ssh/keys-root/authorized_keys'"
