---
- name: Copy SSH key to ESXi hosts
  hosts: esxi
  connection: local

  tasks:
    - name: Copy SSH key to authorized_keys
      shell: cat /root/.ssh/id_rsa.pub | ssh root@{{ ansible_host }} 'cat >> /etc/ssh/keys-root/authorized_keys'
