---
- name: Copy SSH public key to ESXi host
  hosts: esxi
  gather_facts: false
  become: true

  tasks:
    - name: Read SSH public key file on control machine
      slurp:
        src: /root/.ssh/id_rsa.pub
      register: public_key_file

    - name: Copy public key contents to authorized_keys file on ESXi host
      shell: echo "{{ public_key_file.content | b64decode }}" >> /etc/ssh/keys-root/authorized_keys
