- name: Copy SSH key to ESXi hosts
  hosts: esxi
  gather_facts: no
  become: yes

  tasks:
  - name: Set the authorized SSH keys for the root user
    command: scp /root/.ssh/id_rsa.pub root@{{ inventory_hostname }}:/etc/ssh/keys-root/authorized_keys
