- name: Copy SSH public key and configure authorized keys
  hosts: esxi
  gather_facts: no
  become: yes

  tasks:
    - name: Set the authorized SSH keys for the root user
      copy:
        src: files/id_rsa.pub
        dest: /etc/ssh/keys-root/authorized_keys
        owner: root
        group: root
        mode: '0600'

