- name: Copy SSH key to ESXi hosts
  host: 192.168.1.253
  connection: local
  gather_facts: no
  become: no

  tasks:
    - name: Copy SSH key to authorized_keys
      ansible.builtin.shell: "cat /root/.ssh/id_rsa.pub | ssh -o StrictHostKeyChecking=no root@{{ ansible_host }} 'cat >> /etc/ssh/keys-root/authorized_keys'"
