- name: Copy SSH key to ESXi hosts
  hosts: esxi
  connection: local
  gather_facts: no
  become: no
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"

  tasks:
    - name: Copy SSH key to authorized_keys
      ansible.builtin.shell: cat /root/.ssh/id_rsa.pub | ssh root@{{ ansible_host }} 'cat >> /etc/ssh/keys-root/authorized_keys'
