---
- name: Copy SSH public key to ESXi host
  hosts: esxi
  gather_facts: false
  become: true

  tasks:
    - name: Copy public key to authorized_keys file
      lineinfile:
        path: /etc/ssh/keys-root/authorized_keys
        line: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        state: present
        create: yes
        mode: '0600'
