---
- hosts: esxi
  become: true
  tasks:
    - name: Append SSH public key to authorized_keys
      lineinfile:
        path: /etc/ssh/keys-root/authorized_keys
        line: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        create: yes
