- name: Copy SSH key to ESXi hosts
  hosts: esxi
  gather_facts: no
  become: yes

  tasks:
  - name: Set the authorized SSH keys for the root user
    expect:
      command: scp /root/.ssh/id_rsa.pub root@{{ ansible_host }}:/etc/ssh/keys-root/authorized_keys
      responses:
        'Are you sure you want to continue connecting (yes/no)?': 'yes'
    delegate_to: localhost
