---
- name: Copy SSH keys to ESXi hosts
  hosts: esxi
  gather_facts: no
  become: no

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Copy SSH key to authorized_keys
      shell: cat root/.ssh/id_rsa.pub | ssh root@{{ ansible_host }} 'cat >> /etc/ssh/keys-root/authorized_keys'
      delegate_to: localhost
